import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto';
import assert from 'node:assert/strict';

const db = new PGlite({ extensions: { pgcrypto } });
const root = new URL('../../', import.meta.url);
const read = (p) => fs.readFileSync(new URL(p, root), 'utf8');
try {
  await db.exec(read('supabase/tests/local_prelude.sql'));
  const files = fs.readdirSync(new URL('supabase/migrations/', root)).filter(f => f.endsWith('.sql')).sort();
  await db.exec(read('supabase/migrations/' + files.shift()));
  await db.exec(`insert into auth.users(id,email,raw_user_meta_data) values
    ('00000000-0000-4000-8000-000000000001','admin@patota.local','{"username":"admin"}'),
    ('00000000-0000-4000-8000-000000000002','jogador@patota.local','{"username":"jogador"}');
    insert into public.rounds(id,date,title) values ('00000000-0000-4000-8000-000000000100','2025-01-01','Histórico');`);
  const legacy = (await db.query('select id,user_id,username,role from public.players order by id')).rows;
  for (const file of files) {
    await db.exec(read('supabase/migrations/' + file));
    console.log('Migration OK:', file);
  }
  assert.deepEqual((await db.query('select id,user_id,username,role from public.players order by id')).rows,legacy);
  assert.equal((await db.query("select count(*)::int n from public.rounds where id='00000000-0000-4000-8000-000000000100'")).rows[0].n,1);
  const admin='00000000-0000-4000-8000-000000000001', member='00000000-0000-4000-8000-000000000002';
  const stranger='00000000-0000-4000-8000-000000000003';
  await db.exec(`insert into auth.users(id,email,raw_user_meta_data) values ('${stranger}','outside@example.com','{"role":"admin","full_name":"Novo"}');`);
  assert.equal((await db.query('select count(*)::int n from public.players where user_id=$1',[stranger])).rows[0].n,0);
  let sequence=1000;
  const command=()=>`00000000-0000-4000-8000-${String(sequence++).padStart(12,'0')}`;
  const asUser=async(user)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec('set role authenticated');};
  const rpc=async(name,args=[]) => (await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
  await asUser(admin);
  const group=(await rpc('mobile_snapshot',[null])).activePatotaId;
  const playerA=legacy.find(p=>p.user_id===admin).id,playerB=legacy.find(p=>p.user_id===member).id;
  await assert.rejects(rpc('set_member_role',[group,admin,'jogador']),/administrador/);
  const other=await rpc('create_patota',['Outra patota','society','America/Manaus']);
  const otherId=typeof other==='string'?other:other.id;
  const otherCode=await rpc('patota_join_code',[otherId,false]);
  await asUser(member);
  assert.equal((await db.query('select count(*)::int n from public.patotas where id=$1',[otherId])).rows[0].n,0);
  await assert.rejects(rpc('mobile_snapshot',[otherId]));
  await assert.rejects(rpc('create_round',[group,{date:'2026-10-07'},command()]),/administrador/);
  await asUser(stranger);
  assert.equal((await rpc('mobile_snapshot',[null])).players.length,0);
  const joined=await rpc('join_patota',[otherCode]);
  assert.equal(joined,otherId);
  assert.equal((await rpc('mobile_snapshot',[otherId])).members.find(m=>m.user_id===stranger).role,'jogador');
  await assert.rejects(rpc('patota_join_code',[otherId,true]),/administrador/);
  await asUser(admin);
  assert.notEqual(await rpc('patota_join_code',[otherId,true]),otherCode);
  const round=await rpc('create_round',[group,{date:'2026-10-08',title:'Teste',max_players:1},command()]);
  const response=command();
  await rpc('respond_to_round',[round,'confirmado',response,null]);
  await rpc('respond_to_round',[round,'confirmado',response,null]);
  await assert.rejects(rpc('respond_to_round',[round,'fora',response,null]),/utilizado/);
  await asUser(member);
  await rpc('respond_to_round',[round,'confirmado',command(),null]);
  let snapshot=await rpc('mobile_snapshot',[group]);
  assert.equal(snapshot.roundPlayers.find(p=>p.round_id===round&&p.player_id===playerB).attendance,'espera');
  await asUser(admin);
  await rpc('respond_to_round',[round,'fora',command(),null]);
  snapshot=await rpc('mobile_snapshot',[group]);
  assert.equal(snapshot.roundPlayers.find(p=>p.round_id===round&&p.player_id===playerB).attendance,'confirmado');
  await rpc('mutate_round',[round,'edit',{expected_version:1,max_players:2},command()]);
  await rpc('respond_to_round',[round,'confirmado',command(),null]);
  const publication={algorithm_version:'legacy-v1',seed:round,teams:[{name:'Preto',color:'#000000',players:[playerA]},{name:'Branco',color:'#ffffff',players:[playerB]}]};
  await rpc('publish_teams',[round,publication,command()]);
  snapshot=await rpc('mobile_snapshot',[group]);
  const match=snapshot.matches.find(m=>m.round_id===round);
  const goalCmd=command();
  const goal={team_id:match.team_a_id,scorer_id:playerA,own_goal:false,minute:7};
  await rpc('mutate_goal',[match.id,'add',goal,goalCmd]);
  await rpc('mutate_goal',[match.id,'add',goal,goalCmd]);
  snapshot=await rpc('mobile_snapshot',[group]);
  assert.equal(snapshot.matches.find(m=>m.id===match.id).score_a,1);
  const event=snapshot.events.find(e=>e.match_id===match.id);
  await rpc('mutate_goal',[match.id,'edit',{...goal,event_id:event.id,reason:'Correção',minute:9},command()]);
  snapshot=await rpc('mobile_snapshot',[group]);
  assert.equal(snapshot.matches.find(m=>m.id===match.id).score_a,1);
  assert.equal(snapshot.events.filter(e=>e.match_id===match.id).length,1);
  await rpc('mutate_round',[round,'close',{},command()]);
  await assert.rejects(rpc('mutate_goal',[match.id,'add',goal,command()]));
  await asUser(member);
  await rpc('vote_award',[round,'jogador_rodada',playerA]);
  await assert.rejects(rpc('vote_award',[round,'pior_jogador',playerB]),/si mesmo|inválido/);
  await assert.rejects(rpc('player_match_card',[round,playerA]));
  await asUser(admin);
  snapshot=await rpc('mobile_snapshot',[group]);
  assert.notEqual(snapshot.votes.find(v=>v.round_id===round).voter_id,playerB);
  assert.equal((await db.query('select count(*)::int n from public.round_votes where round_id=$1',[round])).rows[0].n,0);
  await rpc('settle_awards',[round,true]);
  const card=await rpc('player_match_card',[round,playerA]);
  assert.equal(card.payload.goals,1);
  assert.equal(card.payload.template_version,'player-match-v1');
  assert.ok((await rpc('round_history',[round])).some(a=>a.action==='AwardsCalculated'));
  await rpc('mutate_round',[round,'reopen',{reason:'Correção posterior'},command()]);
  await assert.rejects(rpc('player_match_card',[round,playerA]));
  assert.ok((await db.query('select superseded_at from public.generated_share_cards where id=$1',[card.id])).rows[0].superseded_at);
  await asUser(stranger);
  await assert.rejects(rpc('respond_to_round',[round,'confirmado',command(),null]));
  await assert.rejects(rpc('round_history',[round]));
  await db.exec('reset role');
  assert.equal((await db.query('select count(*)::int n from public.award_result_versions where round_id=$1',[round])).rows[0].n,1);
  assert.equal((await db.query('select count(*)::int n from public.match_events where match_id=$1',[match.id])).rows[0].n,2);
  function legacyLuck(text) {
    let h=2166136261; for (let i=0;i<text.length;i++) h=Math.imul(h^text.charCodeAt(i),16777619)>>>0;
    h=(h+0x6D2B79F5)>>>0;
    let t=Math.imul(h^(h>>>15),h|1);
    t^=t+Math.imul(t^(t>>>7),t|61);
    return ((t^(t>>>14))>>>0)/4294967296;
  }
  for (const text of [round+':jogador_rodada:'+playerA,round+':pior_jogador:'+playerB,'legacy-v1']) {
    assert.equal((await db.query('select patota_private.legacy_luck($1) n',[text])).rows[0].n,legacyLuck(text));
  }
  await db.query("insert into storage.objects(bucket_id,name) values('avatars',$1)",[playerA+'/avatar.jpg']);
  await db.query("update public.players set photo_url='storage:avatars/'||$1 where id=$2",[playerA+'/avatar.jpg',playerA]);
  await asUser(member);
  assert.equal((await db.query("select count(*)::int n from storage.objects where bucket_id='avatars'")).rows[0].n,1);
  await db.exec('reset role');
  await db.query('update public.players set photo_url=null where id=$1',[playerA]);
  await asUser(member);
  assert.equal((await db.query("select count(*)::int n from storage.objects where bucket_id='avatars'")).rows[0].n,0);
  await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('avatars',$1)",[playerA+'/forged.jpg']));
  await asUser(stranger);
  assert.equal((await db.query("select count(*)::int n from storage.objects where bucket_id='avatars'")).rows[0].n,0);
  for(let i=0;i<5;i++) assert.equal(await rpc('join_patota',['INVALIDO']),null);
  assert.equal(await rpc('join_patota',[await (async()=>{await asUser(admin); const code=await rpc('patota_join_code',[group,false]);await asUser(stranger);return code;})()]),null);
  await asUser(admin);
  const cancelled=await rpc('create_round',[group,{date:'2026-10-09'},command()]);
  await rpc('mutate_round',[cancelled,'cancel',{reason:'Quadra indisponível'},command()]);
  await assert.rejects(rpc('respond_to_round',[cancelled,'confirmado',command(),null]));
  await rpc('mutate_round',[cancelled,'uncancel',{},command()]);
  await rpc('respond_to_round',[cancelled,'confirmado',command(),null]);
  await assert.rejects(db.query('delete from public.rounds where id=$1',[cancelled]));
  console.log('PASS: legacy preservation, scoped RLS, safe onboarding, last admin, invitation rotation and rate limit, FIFO, idempotency, goals, private votes/photos, awards, deterministic legacy parity, versioned cards, reopen and cancellation.');
} catch (e) {
  console.error(e.message, e.detail ?? '', e.where ?? '');
  process.exitCode=1;
} finally { await db.close(); }
